import type { ToolDefinition } from '@/types/tool';

export const TOOL_DEFINITIONS: ToolDefinition[] = [
  {
    slug: 'hooks-generator',
    name: 'Hooks Generator',
    description: 'Generate React, Angular, and Vue hooks/composables with intelligent code generation.',
    longDescription:
      'Our Hooks Generator creates custom React hooks, Angular hooks, or Vue composables tailored to your specific requirements. Perfect for developers looking to streamline their workflow with reusable logic.',
    category: 'Content',
    resultLabel: 'Generated Code',
    fields: [
      {
        id: 'framework',
        label: 'Framework',
        type: 'select',
        options: [
          { label: 'React', value: 'react' },
          { label: 'Angular', value: 'angular' },
          { label: 'Vue', value: 'vue' },
        ],
        required: true,
      },
      {
        id: 'hookName',
        label: 'Hook Name',
        type: 'text',
        placeholder: 'e.g., useLocalStorage',
        required: true,
        maxLength: 50,
      },
      {
        id: 'description',
        label: 'Hook Description',
        type: 'textarea',
        placeholder: 'Describe what this hook should do...',
        helperText: 'Provide a clear description of the functionality you need.',
        required: true,
        maxLength: 500,
      },
    ],
  },
  {
    slug: 'youtube-ideas',
    name: 'YouTube Ideas Generator',
    description: 'Create engaging video titles and descriptions that drive views and engagement.',
    longDescription:
      'Generate compelling YouTube video titles, descriptions, and tags optimized for discoverability and engagement. Perfect for content creators looking to maximize their reach.',
    category: 'Content',
    resultLabel: 'Video Ideas',
    fields: [
      {
        id: 'topic',
        label: 'Video Topic',
        type: 'text',
        placeholder: 'e.g., Next.js 14 App Router',
        required: true,
        maxLength: 100,
      },
      {
        id: 'tone',
        label: 'Tone',
        type: 'select',
        options: [
          { label: 'Informative', value: 'informative' },
          { label: 'Entertaining', value: 'entertaining' },
          { label: 'Educational', value: 'educational' },
          { label: 'Inspiring', value: 'inspiring' },
        ],
        required: true,
      },
      {
        id: 'targetAudience',
        label: 'Target Audience',
        type: 'text',
        placeholder: 'e.g., beginner developers',
        helperText: 'Who is this video for?',
        required: true,
        maxLength: 100,
      },
    ],
  },
  {
    slug: 'blog-outline',
    name: 'Blog Outline Generator',
    description: 'Structure comprehensive blog posts with AI-generated outlines and sections.',
    longDescription:
      'Create detailed blog post outlines with headlines, subheadings, and key points. Perfect for content writers and marketers looking to structure their articles effectively.',
    category: 'Content',
    resultLabel: 'Blog Outline',
    fields: [
      {
        id: 'title',
        label: 'Blog Title',
        type: 'text',
        placeholder: 'e.g., 10 Tips for Better Web Performance',
        required: true,
        maxLength: 150,
      },
      {
        id: 'keywords',
        label: 'Target Keywords',
        type: 'text',
        placeholder: 'web performance, optimization, speed',
        helperText: 'Comma-separated list of keywords',
        required: true,
        maxLength: 200,
      },
      {
        id: 'wordCount',
        label: 'Target Word Count',
        type: 'select',
        options: [
          { label: '500-800 words', value: '500' },
          { label: '1000-1500 words', value: '1000' },
          { label: '2000+ words', value: '2000' },
        ],
        required: true,
      },
    ],
  },
  {
    slug: 'social-captions',
    name: 'Social Captions Generator',
    description: 'Craft platform-specific captions for Instagram, Twitter, LinkedIn, and more.',
    longDescription:
      'Generate engaging social media captions optimized for different platforms. Includes hashtag suggestions and character limits for each platform.',
    category: 'Marketing',
    resultLabel: 'Social Captions',
    fields: [
      {
        id: 'platform',
        label: 'Platform',
        type: 'select',
        options: [
          { label: 'Instagram', value: 'instagram' },
          { label: 'Twitter/X', value: 'twitter' },
          { label: 'LinkedIn', value: 'linkedin' },
          { label: 'Facebook', value: 'facebook' },
        ],
        required: true,
      },
      {
        id: 'content',
        label: 'Content Description',
        type: 'textarea',
        placeholder: 'Describe what your post is about...',
        required: true,
        maxLength: 300,
      },
      {
        id: 'tone',
        label: 'Tone',
        type: 'select',
        options: [
          { label: 'Professional', value: 'professional' },
          { label: 'Casual', value: 'casual' },
          { label: 'Humorous', value: 'humorous' },
          { label: 'Inspirational', value: 'inspirational' },
        ],
        required: true,
      },
    ],
  },
  {
    slug: 'taglines',
    name: 'Taglines Generator',
    description: 'Create compelling marketing taglines and slogans for your brand.',
    longDescription:
      'Generate memorable and impactful taglines for your brand, product, or campaign. Perfect for marketers and entrepreneurs.',
    category: 'Marketing',
    resultLabel: 'Tagline Ideas',
    fields: [
      {
        id: 'brandName',
        label: 'Brand/Product Name',
        type: 'text',
        placeholder: 'e.g., TechFlow',
        required: true,
        maxLength: 50,
      },
      {
        id: 'industry',
        label: 'Industry',
        type: 'text',
        placeholder: 'e.g., SaaS, E-commerce, Education',
        required: true,
        maxLength: 100,
      },
      {
        id: 'values',
        label: 'Brand Values',
        type: 'textarea',
        placeholder: 'Innovation, simplicity, reliability...',
        helperText: 'What does your brand stand for?',
        required: true,
        maxLength: 300,
      },
    ],
  },
  {
    slug: 'seo-brief',
    name: 'SEO Brief Generator',
    description: 'Generate comprehensive SEO briefs with keywords, metadata, and content strategy.',
    longDescription:
      'Create detailed SEO content briefs including keyword research, meta descriptions, content structure, and optimization recommendations.',
    category: 'Marketing',
    resultLabel: 'SEO Brief',
    fields: [
      {
        id: 'topic',
        label: 'Content Topic',
        type: 'text',
        placeholder: 'e.g., Best Project Management Tools',
        required: true,
        maxLength: 150,
      },
      {
        id: 'primaryKeyword',
        label: 'Primary Keyword',
        type: 'text',
        placeholder: 'e.g., project management software',
        required: true,
        maxLength: 100,
      },
      {
        id: 'contentType',
        label: 'Content Type',
        type: 'select',
        options: [
          { label: 'Blog Post', value: 'blog' },
          { label: 'Landing Page', value: 'landing' },
          { label: 'Product Page', value: 'product' },
          { label: 'Guide/Tutorial', value: 'guide' },
        ],
        required: true,
      },
    ],
  },
  {
    slug: 'task-prioritization',
    name: 'Task Prioritization',
    description: 'Organize and prioritize your tasks using the Eisenhower Matrix framework.',
    longDescription:
      'Automatically categorize your tasks into urgent/important quadrants to help you focus on what matters most.',
    category: 'Productivity',
    resultLabel: 'Prioritized Tasks',
    fields: [
      {
        id: 'tasks',
        label: 'Tasks List',
        type: 'textarea',
        placeholder: 'Enter your tasks, one per line...',
        helperText: 'Enter each task on a new line',
        required: true,
        maxLength: 1000,
      },
    ],
  },
  {
    slug: 'color-palette',
    name: 'Color Palette Generator',
    description: 'Create beautiful color palettes with hex codes and CSS variables.',
    longDescription:
      'Generate harmonious color palettes perfect for web design, branding, and UI projects. Export as CSS variables or Tailwind config.',
    category: 'Design',
    resultLabel: 'Color Palette',
    fields: [
      {
        id: 'baseColor',
        label: 'Base Color (Hex)',
        type: 'text',
        placeholder: '#3B82F6',
        helperText: 'Enter a hex color code',
        required: true,
        maxLength: 7,
      },
      {
        id: 'scheme',
        label: 'Color Scheme',
        type: 'select',
        options: [
          { label: 'Analogous', value: 'analogous' },
          { label: 'Complementary', value: 'complementary' },
          { label: 'Triadic', value: 'triadic' },
          { label: 'Monochromatic', value: 'monochromatic' },
        ],
        required: true,
      },
    ],
  },
];
